[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Retina" }
size = 14

[keyboard]
bindings = [
    { key = "Left", mods = "Option", chars = "\u001BB" },
    { key = "Right", mods = "Option", chars = "\u001BF" },
]
